name: Deploy Repository

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      package_url:
        required: false
        type: string
      package_name:
        required: false
        type: string
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download package
        if: inputs.package_url != ''
        run: |
          mkdir -p packages
          curl -L "${{ inputs.package_url }}" -o "packages/${{ inputs.package_name }}"

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-utils gnupg xz-utils zstd bzip2 lz4 gzip gawk

      - name: Import GPG key
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "$GPG_KEY" | gpg --import
          
      - name: Update Repository
        run: |
          chmod +x updaterepo.sh
          ./updaterepo.sh

      - name: Commit & Push changes
        if: inputs.package_url != ''
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          default_author: github_actions
          fetch: false
          message: 'chore(repo): update packages [skip ci]'
          push: true

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4