name: Deploy Repository

on:
  workflow_call:
    inputs:
      package_url:
        required: false
        type: string
      package_name:
        required: false
        type: string
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download package
        if: inputs.package_url != '' && inputs.package_name != ''
        run: |
          curl -L "${{ inputs.package_url }}" -o "packages/${{ inputs.package_name }}"

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-utils xz-utils zstd bzip2 lz4 gzip
          
      - name: Import GPG key
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "$GPG_KEY" | gpg --import
          KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | cut -d'/' -f2 | cut -d' ' -f1)
          echo "GPG_KEY_ID=$KEY_ID" >> $GITHUB_ENV
          
      - name: Update Repository
        env:
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          CI: true
        run: |
          chmod +x update-repo.sh
          ./update-repo.sh

      - name: Commit & Push changes
        if: inputs.package_url != ''
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          default_author: github_actions
          fetch: false
          message: 'chore(repo): update packages [skip ci]'
          push: true

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4